# Deep learning from Scratch


In [9]:
# chap 1: python
# type  
print(type(10))

# array - list
a = [1, 2, 3, 4, 5]
print(a[2:])
print(a[:2])

# dict
me = {'firstName': "Bob", 'lastName': "Jackson"}
print(me["firstName"])

# Boolean and condition
hungry = False
if hungry == False: 
    print("Please offer some food")
else:
    print("I'm stuffed")

# for loop
for i in [0, 1, 2, 3]:
    print(i)

# funtion
def helo(name):
    return "Hello {0}!".format(name)

print(helo("Bob"))


<class 'int'>
[3, 4, 5]
[1, 2]
Bob
Please offer some food
0
1
2
3
Hello Bob!


In [10]:
# class implementation

class Fraction:
    def __init__(self, numerator, denominator):
        self.numerator = numerator
        self.denominator = denominator

    def __str__(self):
        return f"{self.numerator}/{self.denominator}"

    def __add__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        num = self.numerator * other.denominator + other.numerator * self.denominator
        den = self.denominator * other.denominator
        return Fraction(num, den)

    def __sub__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        num = self.numerator * other.denominator - other.numerator * self.denominator
        den = self.denominator * other.denominator
        return Fraction(num, den)

    def __mul__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        num = self.numerator * other.numerator
        den = self.denominator * other.denominator
        return Fraction(num, den)

    def __truediv__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        num = self.numerator * other.denominator
        den = self.denominator * other.numerator
        return Fraction(num, den)

    def __eq__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        return self.numerator * other.denominator == other.numerator * self.denominator

    def __lt__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        return self.numerator * other.denominator < other.numerator * self.denominator

    def __le__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        return self.numerator * other.denominator <= other.numerator * self.denominator

    def __gt__(self, other):
        if isinstance(other, int):
            other = Fraction(other, 1)
        return self.numerator * other.denominator > other.numerator


In [14]:
# 
f1 = Fraction(1, 3)
f2 = Fraction(2, 5)
print(f1, f2)
print(f1+f2, f1-f2, f1*f2, f1==f2)


1/3 2/5
11/15 -1/15 2/15 False


In [30]:
# numpy
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x/2.0)

x = np.array([[1,2], [3,4], [5,6]])
print(x/2.0)
print(x.shape)
row, col = x.shape
print("the first:seconde dimention:{0}:{1}".format(x.shape[0], x.shape[1]))

y = np.array([10, 20])
print(y.shape)
print(x*y)

z = np.array([[10], [20], [30]])
print(x*z)

# np中的array并不是行和列的关系，准确的是列和行
for i in x:
    print(i)


[0.5 1.  1.5]
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
(3, 2)
the first:seconde dimention:3:2
(2,)
[[ 10  40]
 [ 30  80]
 [ 50 120]]
[[ 10  20]
 [ 60  80]
 [150 180]]
[1 2]
[3 4]
[5 6]
